Update to version 1.59.0
flathub/com.visualstudio.code pull request #240
Opened 2021-08-08 02:28 UTC by jeffteixeira

2021-08-11 18:23 UTC, teohhanhui commented
https://docs.flatpak.org/en/latest/electron.html#the-electron-base-app

https://github.com/refi64/zypak/blob/master/README.md#basic-usage

2021-09-14 19:38 UTC, BEEDELLROKEJULIANLOCKHART approved these changes

2021-09-14 19:41 UTC, BEEDELLROKEJULIANLOCKHART requested changes
The 92nd line should be http://packages.microsoft.com/repos/code/pool/main/c/code/code_1.60.1-1631294805_amd64.deb.

2021-09-30 20:58 UTC, barthalion commented
Superseded by https://github.com/flathub/com.visualstudio.code/pull/251

2021-09-30 20:58 UTC, closed without merging